version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: productflow-db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Senha do usuário root
      MYSQL_DATABASE: ${MYSQL_DATABASE}  # Nome do banco de dados
      MYSQL_USER: ${MYSQL_USER}  # Usuário para a aplicação
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  # Senha do usuário da aplicação
    ports:
      - "3307:3306"  # Mudando a porta externa para 3307, já que 3306 está sendo usada no seu sistema
    networks:
      - productflow_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      retries: 5

  web:
    build: .
    container_name: productflow-web
    command: bash -c "dockerize -wait tcp://db:3306 -timeout 60s python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    environment:
      - MYSQL_HOST=db  # Nome do serviço do banco de dados
      - MYSQL_PORT=3306  # Porta interna do banco de dados
      - MYSQL_USER=${MYSQL_USER}  # Usuário do banco de dados
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}  # Senha do banco de dados
      - MYSQL_DATABASE=${MYSQL_DATABASE}  # Nome do banco de dados
    ports:
      - "8000:8000"  # Porta externa 8000
    depends_on:
      - db  # A aplicação web depende do banco de dados
    networks:
      - productflow_net
    restart: always

networks:
  productflow_net:
    driver: bridge

volumes:
  mysql_data:
    driver: local
